sudo: required
services:
    - docker

before_install:
    - docker build -f ./client/Dockerfile.dev -t omidmafi/react-test ./client

script:
    - docker run -e CI=true omidmafi/react-test npm run test

after_success:
    - docker build -t omidmafi/multi-client ./client
    - docker build -t omidmafi/multi-nginx ./nginx
    - docker build -t omidmafi/multi-worker ./worker
    - docker build -t omidmafi/multi-server ./server

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    - docker push omidmafi/multi-client
    - docker push omidmafi/multi-nginx
    - docker push omidmafi/multi-server
    - docker push omidmafi/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    name: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-698985873767"
    bucket_path: "multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY
    